use_default_settings: true

search:
  autocomplete: "quark"
  formats:
    - html
    - json

server:
  secret_key: "%(ENV_SEARXNG_SECRET)s"  
  limiter: true
  image_proxy: true
  
general:
  instance_name: LibreSearch

ui:
  static_use_hash: true
  default_theme: simple
  theme_args:
    simple_style: dark
  infinite_scroll: true
  results_on_new_tab: true

enabled_plugins:
  - Basic Calculator
  - Hash plugin
  - Hostnames plugin
  - Open Access DOI rewrite
  - Self Informations
  - Tracker URL remover
  - Unit converter plugin
