use_default_settings: true

search:
  autocomplete: "quark"
  formats:
    - html
    - json

server:
  secret_key: "%(ENV_SEARXNG_SECRET)s"  
  limiter: true
  image_proxy: true
  
general:
  instance_name: Libre Search

plugins:
  searx.plugins.calculator.SXNGPlugin:
    active: true
  searx.plugins.hash_plugin.SXNGPlugin:
    active: true
  searx.plugins.self_info.SXNGPlugin:
    active: true
  searx.plugins.unit_converter.SXNGPlugin:
    active: true
  searx.plugins.ahmia_filter.SXNGPlugin:
    active: true
  searx.plugins.hostnames.SXNGPlugin:
    active: true
  searx.plugins.oa_doi_rewrite.SXNGPlugin:
    active: true
  searx.plugins.tor_check.SXNGPlugin:
    active: false
  searx.plugins.tracker_url_remover.SXNGPlugin:
    active: true
    
ui:
  static_use_hash: true
  default_theme: simple
  theme_args:
    simple_style: light
  infinite_scroll: true
  results_on_new_tab: true

enabled_plugins:
  - Basic Calculator
  - Hash plugin
  - Hostnames plugin
  - Open Access DOI rewrite
  - Self Informations
  - Tracker URL remover
  - Unit converter plugin
