use_default_settings: true
search:
  autocomplete: "duckduckgo"
  formats:
    - html
    - json
server:
  secret_key: "%(ENV_SEARXNG_SECRET)s"  # change this!
  limiter: true  # can be disabled for a private instance
  image_proxy: true
ui:
  static_use_hash: true
engines:
  - name: pixiv
    disabled: false
    pixiv_image_proxies:
      - https://pximg.cocomi.eu.org
    
  - name: brave
    engine: brave
    shortcut: br
    time_range_support: true
    paging: true
    disabled: false
    categories: [general, web]
    brave_category: search
