# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
search:
  autocomplete: "duckduckgo"
  formats:
    - html
    - json
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "%(ENV_SEARXNG_SECRET)s"  # change this!
  limiter: true  # can be disabled for a private instance
  image_proxy: true
ui:
  static_use_hash: true
engines:
  - name: pixiv
    disabled: false
    pixiv_image_proxies:
      - https://pximg.cocomi.eu.org