use_default_settings: true
search:
  autocomplete: "duckduckgo"
  formats:
    - html
    - json
server:
  secret_key: "%(ENV_SEARXNG_SECRET)s"  # change this!
  limiter: true  # can be disabled for a private instance
  image_proxy: true
ui:
  static_use_hash: true
engines:    
  - name: brave
    engine: brave
    shortcut: br
    time_range_support: true
    paging: true
    disabled: true
    categories: [general, web]
    brave_category: search

  - name: startpage
    engine: startpage
    shortcut: sp
    startpage_categ: web
    disabled: true
    categories: [general, web]
    additional_tests:
      rosebud: *test_rosebud
